name=VPinLedController
version=1.0.0
author=LSatan
maintainer=LSatan
sentence=High Performance 16-Channel DMA Controller for Virtual Pinball
paragraph=Custom Ethernet and NeoPixelBus wrapper for 60MHz SPI and dynamic memory allocation.
category=Display
url=
architectures=esp32
includes=VPinLedControllerUsb.h,VPinLedControllerWifi.h,VPinLedControllerEthernet.h